### ISSUE TITLE
Location tracking needs to be enabled on all maps

### ISSUE THREAD

**Issue by zinfin** [Esri/maps-app-android#123]
Currently when maps-app starts up with the default basemap, the floating action button in the lower right corner of the app screen can be used to toggle location tracking on and off.  This functionality isn't enabled in maps loaded from a portal (e.g. user content from ArcGISOnline).

This is not specific to any hardware or Android OS version.

To reproduce, start the app and note how the floating action button responds to touch by toggling location tracking on/off.  Next, sign in to view your content on an ArcGISOnline repository and load a map.  Note that the floating action button no longer triggers location tracking.

**Comment by doneill** [comment]
Verified with #127
