### ISSUE TITLE
Compass icon gets out of sync with map orientation after toggling location tracking

### ISSUE THREAD

**Issue by zinfin** [Esri/maps-app-android#124]
When the map-app initially loads, clicking the floating action button enables location tracking.  The navigation compass appears in the upper right corner of the screen, with the red arrow pointing north in the map. Clicking the floating action button again toggles location tracking off.  The compass is still visible and seems to stay in sync with the map, but after repeatedly toggling the floating action button and rotating the map note that the compass begins to get out of sync with the map.
Hardware Nexus 7, Android version 5.1.1.

**Comment by zinfin** [comment]
@doneill  See PR #131

**Comment by doneill** [comment]
Verified with PR #134
