### ISSUE TITLE
Android soft keyboard appears after switching basemaps

### ISSUE THREAD

**Issue by doneill** [Esri/maps-app-android#135]
Need to investigate further as to why the soft keyboard is appearing after switching basemaps.

**Comment by zinfin** [comment]
This is still an issue and wasn't resolved by [issue 133](https://github.com/Esri/maps-app-android/issues/133).  The problem appears to be related to a focus change listener on the search view being triggered when the drawer layout opens and closes (`setOnQueryTextFocusChangeListener`).

**Comment by doneill** [comment]
Verified fixed
