### ISSUE TITLE
Loading maps extent

### ISSUE THREAD

**Issue by marastoica** [Esri/maps-app-android#138]
@zinfin I have a suggestion regarding maps. When a user signs in and loads a map, I think the app should zoom/pan to the extent of the map rather than to the user's current location. And if they want to be zoomed to their current location, all they have to do is click the Current Location button.

**Comment by doneill** [comment]
@marastoica That is valid UX suggestion, we still need to zoom into current location when extent of map to full extent, e.g. default basemaps as web map.

**Comment by willcrick** [comment]
I would suggest we keep it as-is. Most mobile mapping applications start off based on the users current location, as it is expected that they have opened the app on a mobile device whilst out and about to see what is around them. The desktop experience should probably be different though...
