### ISSUE TITLE
How to find the hospitals nearby along with the insurance card available in that hospital,Just like the search widget in cmv Template,how can i develop an app based on this requirement

### ISSUE THREAD

**Issue by pnh10** [Esri/maps-app-android#139]
Having  hospitals data along with insurance card category is available ,I would like to develop the app to find nearby locations to the current location based on the insurance card category  available over it.

i.e. Nearby Hospitals with condition of insurance category for current location

**Comment by doneill** [comment]
@pnh10 This app does not support nearby search capabilities.  Please post questions like these to our [GeoNet forum](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for broader ArcGIS Android questions.
