### ISSUE TITLE
Crash when signing into a portal

### ISSUE THREAD

**Issue by eric906** [Esri/maps-app-android#148]
Using "build_1517" branch.
Crashes on device or emulator.
Device tested is API 23.

To repro:

- Start the app and click Sign In.
- Click 'continue', with www.arcgis.com
- A browser opens, and the message says: "invalid client_id" "error: 400"
- Now, hit the back button on the device. Until it brings the app back to the forefront.

The app will crash, and restart.

cc @zinfin

**Comment by zinfin** [comment]
@eric906 I've checked in a fix to this branch, updating the doc and bringing the runtime version up to build 1522.  Please give this latest a try!

**Comment by eric906** [comment]
@zinfin Great, Sandi. Thank you! I'll give it a whirl.
So, for my understanding, if I don't do what the doc tells me to do....i will still experience a crash. Correct?

**Comment by zinfin** [comment]
@eric906 Correct.  Please give the master branch a try.

**Comment by doneill** [comment]
Closing as fixed
