### ISSUE TITLE
Would like to use maps-app-android when on airplane mode but connected to wi-fi

### ISSUE THREAD

**Issue by shellygill** [Esri/maps-app-android#154]
My scenario is I have a test device that I keep on airplane mode (my SIM card is for occasional testing, but day-to-day I dont want to use any mobile network data - I just want to stick to wi-fi usage).  I so have a wi-fi connection (this can be turned back on independently after having gone into airplane mode).

When I start the maps app on this device, I get the dialog asking me to go to settings to turn off airplane mode.

I think this dialog should not be shown in my case - I have network connection, and my current location can also be ascertained, via wi-fi.

@zinfin

**Comment by zinfin** [comment]
@shellygill I've created a fix in this [PR](https://github.com/Esri/maps-app-android/pull/155) if you want to test it.

**Comment by shellygill** [comment]
Commented in PR - change works well for me.
