### ISSUE TITLE
Do not recenter map at device location if opening a pre-existing map

### ISSUE THREAD

**Issue by shellygill** [Esri/maps-app-android#156]
When I log in to my organization, pick 'My maps', and then tap a map to open this pre-existing map, the map then recenters at the current device location.

However, most of my maps are unrelated to my current location, so this app behaviour does not work for this case.

Perhaps the LocationDisplay should not be activated if the map that's being opened is a pre-existing map? (User could always activate the LocationDisplay afterwards if required).

@zinfin

**Comment by zinfin** [comment]
@shellygill see this closed issue where @willcrick  commented on this....https://github.com/Esri/maps-app-android/issues/138.  I like your idea though.  It would be nice to toggle centering to my location.

**Comment by shellygill** [comment]
Ah, thanks @zinfin - I should have check existing issues! Right, time to fork...
