### ISSUE TITLE
Show 'My Org Maps' item alongside 'My Maps' if I'm signed in to an organization

### ISSUE THREAD

**Issue by shellygill** [Esri/maps-app-android#159]
When I sign in to an organization I'd like to be able to easily see the featured maps for my organization.

This could be another choice in the navigation drawer, beneath 'My Maps'. Choosing this could show a list of maps in the same way as 'My Maps', likewise with the ability to open each map.

@zinfin

**Comment by zinfin** [comment]
@shellygill A naive question about featured maps.  How are featured maps designated in AGOL?  Is this a specific group?  Do all orgs have a default feature map grouping (which could be empty)?

**Comment by shellygill** [comment]
@zinfin As the org admin, , yes, you basically designate a group which contains featured items. But from the API POV, there's an API which helps you get the featured items:
- https://developers.arcgis.com/android/latest/guide/search-for-content.htm#ESRI_SECTION1_5AC3764A84B1478C9F5A35F562E786FD

**Comment by zinfin** [comment]
@shellygill Check out the featured_content branch and let me know if it meets your needs.  It's a first pass and needs some more work, but wanted to know if it's headed in the right direction.

**Comment by shellygill** [comment]
Thanks @zinfin - this worked for me. To use this effectively I will need to fork and make a change to avoid setting the location display to recenter when opening one of the featured maps, in order to see the map content. I got a list of the UK basemaps in featured content when not signed in - that's what I see in ArcGIS online when connecting anonymously in the UK so makes sense.

**Comment by zinfin** [comment]
@willcrick @doneill  I think it's worth considering Shelly's request to be able turn off location display in the maps app, given the context that maps and featured content may well be focused away from the device location.

**Comment by doneill** [comment]
@zinfin @shellygill I will look into the use case.

**Comment by doneill** [comment]
@shellygill @zinfin I find the featured content to be a bit confusing, when not logged I get random maps that don't make much sense, so not sure what the app is trying to feature. Then when I do log in the featured content makes even less sense:  

![features](https://cloud.githubusercontent.com/assets/1308001/20697477/5facd0e0-b5ae-11e6-9d3e-34b9e1fd412c.png)

I think this needs more thought around what is actually featured.  In the mean time this seems to be an excellent example of how to extend the maps-app to add custom features.

**Comment by shellygill** [comment]
@doneill They're probably from the Gallery. I find lots of UK based maps, similar to the ones shown in the old ArcGIS.com home page when accessing from the UK (I guess that design has changed though). I don't have a strong opinion on showing it or not, for anonymous usage, expect it to be more useful for authenticated organization users though.

**Comment by doneill** [comment]
@shellygill I agree with the expectation of it being more useful for authenticated users and that it should be compelling as to what it is adding to the app users experience.  Maybe categories under featured content more aligned to the [ready to use maps](http://www.arcgis.com/features/maps/index.html)?  Although that may be a use case for an independent example app 😄 .

**Comment by doneill** [comment]
This feature will not be implemented in the app but rather as an example of extending the app.
