### ISSUE TITLE
Build fails finding android.arch.lifecycle 'runtime' dependency

### ISSUE THREAD

**Issue by shellygill** [Esri/maps-app-android#171]
The build currently fails as the expected version of this dependency is not found in the jcenter repository.

The jcenter repository is searched as I think it does have some versions of this dependency, but fails when the expected version is not found. The google repository does have the expected version but it's lower down in the repositories list and so is not searched first.

Should also keep the bintray public URL for the maven repository.

**Comment by mikewilburn** [comment]
Thanks for logging this one @shellygill. We'll try to get @fallsdownhill on it soon.

**Comment by fallsdownhill** [comment]
I didn't see the "finding android.arch.lifecycle 'runtime' " failure, but I've pulled out the extra maven repo as part of the above PR

**Comment by fallsdownhill** [comment]
Should be fixed as of the above PR.
