### ISSUE TITLE
Create a scale bar tool

### ISSUE THREAD

**Issue by doneill** [Esri/maps-app-android#39]
Scale bar tool was requested by dev summit 2014 session attendees who were exposed to the measure tool.

**Comment by doneill** [comment]
Measure tool is removed.

**Comment by lanetteamkaushal** [comment]
Hi @doneill,

Is there any method or tools for developer that can be use to create scale bar tool ?

**Comment by doneill** [comment]
@lanetteamkaushal Unfortunately we don't have a high level API for this currently.  We have removed measure capabilities in the app are no longer looking to include it.  On the bright side we still feel this is a valid tool to include and will most likely investigate post Quartz release.

**Comment by lanetteamkaushal** [comment]
Okay Thanks @doneill !
Looking forward for this feature!
