### ISSUE TITLE
Make Map available offline

### ISSUE THREAD

**Issue by doneill** [Esri/maps-app-android#42]
Provide feature and workflow for viewing maps when offline.  

**Feature**
- [ ] Taking basemap offline
- [ ] Set a reasonable extent such that the user does not have to select Tile Levels as all levels below extent should be taken by default.  

**Workflow**
**User initiated** 
- [ ] Add a icon and text in the drawer
- [ ] The app will use the existing extent as candidate for offline. 

**Auto**
- [ ] App automatically caches areas where the user has been.  There will be a defined limit on space and saved to app data space.  These tiles will be private to the app and should be placed in the directory returned by `Context.getExternalFilesDir` then the system will take care of deleting if the app is uninstalled.  With Android 4.4 we can use `getExternalCacheDir()`.

**Comment by fallsdownhill** [comment]
To get an example of the offline usage, you can use this app instead: https://github.com/Esri/mapbook-android

It's unlikely that offline functionality will be added to this app.
